rails_home_link: "https://www.railstutorial.org/"
rails_help_link: "https://www.railstutorial.org/help"
rails_book_link: "https://www.railstutorial.org/book"
rails_author_link: "https://www.michaelhartl.com/"
rails_news_link: https://news.railstutorial.org/"
gravatar_home_link: "https://gravatar.com/emails"

name:
  length:
    max: 50
email:
  length:
    max: 50
  valid_regex: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
password:
  length:
    min: 6
avatar:
  size:
    profile: 80
    list: 50
user:
  admin:
    name: "Tran Anh Tuan"
    email: "tatuan19@gmail.com"
    password: "123456"
  faker:
    password: "password"
